"""empty message

Revision ID: 95f64c070b2e
Revises: f4fd06ffd8e8
Create Date: 2019-11-17 02:02:03.538484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f64c070b2e'
down_revision = 'f4fd06ffd8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET admin=False")
    op.alter_column("users", "admin", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
