"""empty message

Revision ID: f4fd06ffd8e8
Revises: 966d3293b2e2
Create Date: 2019-10-15 22:02:54.216421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fd06ffd8e8'
down_revision = '966d3293b2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute("UPDATE users SET password=email")
    op.alter_column("users", "password", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
